name 'puppet-pushover'
version '0.0.1'
license 'Apache 2.0'
summary 'Report processor that sends a push-notification by Pushsafer about failed Puppet runs'
project_page 'https://github.com/appzer/puppet-pushsafer'
